# Generated by Django 4.0.3 on 2023-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
