# Generated by Django 4.0.3 on 2023-01-28 08:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_alter_groupquestion_time_questionattended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 14, 23, 16, 34425), null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
