# Generated by Django 4.0.3 on 2023-01-28 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_alter_groupquestion_time_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 14, 23, 42, 448859), null=True),
        ),
    ]
