# Generated by Django 4.0.3 on 2023-02-01 13:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_alter_groupquestion_time_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 18, 44, 13, 708114), null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
