# Generated by Django 4.1.5 on 2023-02-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_alter_groupquestion_time_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 0, 11, 29, 146300), null=True),
        ),
    ]
