# Generated by Django 4.0.3 on 2023-01-11 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 22, 21, 50, 216200), null=True),
        ),
    ]
