# Generated by Django 4.0.3 on 2023-01-12 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 14, 21, 31, 751681), null=True),
        ),
    ]
