# Generated by Django 4.0.3 on 2023-02-01 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_alter_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 18, 44, 13, 710104), null=True),
        ),
    ]
