# Generated by Django 4.1.5 on 2023-02-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0010_alter_like_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 7, 0, 11, 29, 148271), null=True),
        ),
    ]
