# Generated by Django 4.0.3 on 2023-01-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.CharField(default='False', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
