# Generated by Django 4.0.3 on 2023-01-12 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_user_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 14, 21, 31, 741481), null=True),
        ),
    ]
