# Generated by Django 4.1.5 on 2023-01-29 17:30

import datetime
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_image_url_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 29, 23, 0, 23, 844857), null=True),
        ),
    ]
