# Generated by Django 4.0.3 on 2023-02-01 13:11

import datetime
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_image_url_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to=user.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 18, 40, 59, 29895), null=True),
        ),
    ]
